# Wiki > https://github.com/Jakubson/AntiAura/wiki/File-config.yml
bot:
    enable: true
    distance: 3.0
    height: 1.0
    bot-hidden-distance: 1.5
    bot-amount: DOUBLE
    bot-show-in-pvp: false
    bot-show-in-pvp-options:
        time: 3
        steps: 20
        player-hits: 10
        reset-player-hits: 40
        enemies-rage: 4
        enemies-in-rage: 3
    report:
        report-amount: 5
        check-time: 30
    visible-on-tablist: true
    visible-for-player: true
    visible-bot-equipment: false
    visible-bot-when-falling: true
    auto-check: false
    auto-check-duration: 30
    auto-check-every: 300
    download-skin: true
    name-type: CUSTOM
    names:
        - 'Jakubson'
        - 'Mimik1337'
        - 'md_5'
        - 'skkf'
        - 'ServerAdmin'
        - 'Herobrine'
        - 'Hypixel'
    disable-worlds:
        - 'map1'
        - 'map2'
messages:
    report:
        enter-player-name: ' §c§l⚠§r §7Enter player name and reason!'
        player-is-offline: ' §c§l⚠§r §7Player is offline!'
        player-reported: ' §c§l⚠§r §7This player already reported by you!'
        thanks-for-report: ' §a§l»§r §7Thanks you for report!'
    reload: '&a&lServer reload! Please join again in a few seconds!'
warn:
    amount: 15
    command: 'kick %PLAYER% Turn off your cheats!'
ban:
    amount: 30
    command: 'ban %PLAYER% Kill aura!'

