bot:
    enable: true
    distance: 3.0
    height: 1.0
    bot-hidden-distance: 1.5
    bot-amount: SINGLE
    bot-show-in-pvp: true
    visible-on-tablist: true
    visible-for-player: false
    visible-bot-equipment: false
    name-type: CUSTOM
    names:
        - 'Jakubson'
        - 'Mimik1337'
        - 'md_5'
        - 'skkf'
        - 'ServerAdmin'
        - 'Herobrine'
        - 'Entity303'
    disable-worlds:
        - 'map1'
        - 'map2'
warn:
    amount: 10
    command: 'kick %PLAYER% Turn off your cheats!'
ban:
    amount: 20
    command: 'ban %PLAYER% Kill aura!'
