bot:
    enable: true
    distance: 3.0
    height: 1.0
    bot-hidden-distance: 1.5
    bot-amount: SINGLE
    bot-show-in-pvp: true
    bot-show-in-pvp-options:
        player-hits: 10
        reset-player-hits: 40
        enemies-rage: 4
        enemies-in-rage: 3
    visible-on-tablist: true
    visible-for-player: false
    visible-bot-equipment: false
    visible-bot-when-falling: true
    download-skin: true
    name-type: CUSTOM
    names:
        - 'Jakubson'
        - 'Mimik1337'
        - 'md_5'
        - 'skkf'
        - 'ServerAdmin'
        - 'Herobrine'
        - 'Entity303'
    disable-worlds:
        - 'map1'
        - 'map2'
messages:
    reload: '&a&lServer reload! Please join again in a few seconds!'
warn:
    amount: 10
    command: 'kick %PLAYER% Turn off your cheats!'
ban:
    amount: 20
    command: 'ban %PLAYER% Kill aura!'
