bot:
    enable: true
    distance: 3
    height: 1
    visible-on-tablis: true
    visible-for-player: true
    name-type: CUSTOM
    names:
        - '§8§kServerBot'
        - '§cJakubson'
        - '§6md_5'
    disable-worlds:
        - 'map1'
        - 'map2'
ban:
    amount: 5
    command: 'ban %PLAYER% Kill aura!'
